// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe9TvYDKyZiCch5YdGHM4D_9ccuKGPAkc',
    appId: '1:476255505870:ios:a6282917f631053082ef9f',
    messagingSenderId: '476255505870',
    projectId: 'device-streaming-128729da',
    storageBucket: 'device-streaming-128729da.firebasestorage.app',
    iosBundleId: 'com.example.advanceResearchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe9TvYDKyZiCch5YdGHM4D_9ccuKGPAkc',
    appId: '1:476255505870:ios:a6282917f631053082ef9f',
    messagingSenderId: '476255505870',
    projectId: 'device-streaming-128729da',
    storageBucket: 'device-streaming-128729da.firebasestorage.app',
    iosBundleId: 'com.example.advanceResearchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxbrny6xY1W-uikCt73B7CJKkfl0o9QH4',
    appId: '1:476255505870:web:a64d90e4de5e785f82ef9f',
    messagingSenderId: '476255505870',
    projectId: 'device-streaming-128729da',
    authDomain: 'device-streaming-128729da.firebaseapp.com',
    storageBucket: 'device-streaming-128729da.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbrny6xY1W-uikCt73B7CJKkfl0o9QH4',
    appId: '1:476255505870:web:a64d90e4de5e785f82ef9f',
    messagingSenderId: '476255505870',
    projectId: 'device-streaming-128729da',
    authDomain: 'device-streaming-128729da.firebaseapp.com',
    storageBucket: 'device-streaming-128729da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsDj0pPqV2vRWTzeD5zMS1-LhOq-osKTU',
    appId: '1:476255505870:android:17d7038124a9d17f82ef9f',
    messagingSenderId: '476255505870',
    projectId: 'device-streaming-128729da',
    storageBucket: 'device-streaming-128729da.firebasestorage.app',
  );

}